paths:
  pdf_documents: ./data/documents
  faiss_store: ./faiss_store

indexing:
  chunk_size: 384
  overlap: 30
  model_name: sentence-transformers/all-MiniLM-L6-v2
  batch_size: 64

modules:
  parser:
    module: model.indexing.parser
    functions:
      - load_all_pdfs
  chunking:
    module: model.indexing.chunking
    functions:
      - chunk_documents
  embeddings:
    module: model.indexing.embeddings
    functions:
      - embed_texts
  vector_store:
    module: model.indexing.vector_store
    functions:
      - save_faiss_index
